name: Build and Release

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        java: [ '21' ]
      fail-fast: false
    name: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configuration de Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: gradle

      # Ajout d'une étape pour générer le wrapper si nécessaire
      - name: Setup Gradle Wrapper
        run: |
          if [ ! -f "./gradlew" ]; then
            gradle wrapper --gradle-version 8.11
          fi
        shell: bash

      - name: Gradle Permission
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: chmod +x ./gradlew

      # Vérifier que le wrapper fonctionne
      - name: Verify Gradle Wrapper
        run: ./gradlew --version
        shell: bash

      - name: Installation des dépendances Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot binutils

      - name: Compilation
        run: ./gradlew jpackage

      - name: Package application
        run: ./gradlew package
        shell: bash

      - name: artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FinanceManager-${{ runner.os }}
          path: |
            build/jpackage/*.deb
            build/jpackage/*.msi
            build/jpackage/*.pkg
            build/jpackage/*.dmg

      - name: Create release github
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/jpackage/*.deb
            build/jpackage/*.msi
            build/jpackage/*.pkg
            build/jpackage/*.dmg
          draft: false
          prerelease: false